myproject/core/urls.py
from django.urls import path
from myproject.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.Index.as_view(), name='index'),
    path('home/', v.home, name='home'),
    path('book/', v.BookList.as_view(), name='book_list'),
    path('book/<int:pk>/', v.book_detail, name='book_detail'),
    path('book/book/<int:pk>/', v.BookDetail.as_view(), name='book_detail'),
    path('book/add/', v.book_add, name='book_add'),
    path('book/book/add/', v.BookCreate.as_view(), name='book_add'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField('título', max_length=200)
    author = models.CharField('autor', max_length=200)
    year_publication = models.PositiveIntegerField(
        'ano de publicação',
        null=True,
        blank=True
    )
    publisher = models.CharField(
        'editora',
        max_length=100,
        null=True,
        blank=True
    )
    cover = models.URLField('capa', null=True, blank=True)

    class Meta:
        verbose_name = "Livro"
        verbose_name_plural = "Livros"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:book_detail', kwargs={'pk': self.pk})

myproject/core/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'author', 'year_publication', 'publisher')

myproject/core/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from .models import Book
from .forms import BookForm


def home(request):
    return HttpResponse('<h1>Bookstore</h1>')


def index(request):
    context = {}
    book_list = Book.objects.all()
    context['book_list'] = book_list
    return render(request, 'index.html', context)


class Index(View):

    def get(self, request):
        context = {}
        book_list = Book.objects.all()
        context['book_list'] = book_list
        return render(request, 'index.html', context)


class BookList(TemplateView):
    model = Book
    template_name = 'core/book_list.html'

    def get_context_data(self, **kwargs):
        context = {}
        book_list = Book.objects.all()
        context['book_list'] = book_list
        return context


class BookList(ListView):
    model = Book
    template_name = 'core/book_list.html'
    context_object_name = 'book_list'


def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    context = {}
    context['book'] = book
    return render(request, 'core/book_detail.html', context)


class BookDetail(DetailView):
    model = Book
    template_name = 'core/book_detail.html'
    context_object_name = 'book'


def book_add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:book_list')
    else:
        form = BookForm()
    context = {'form': form}
    return render(request, 'core/book_add.html', context)


class BookCreate(CreateView):
    model = Book
    template_name = 'core/book_add.html'
    form_class = BookForm

myproject/core/templates/base.html
{% load static %}
<!-- https://startbootstrap.com/template-overviews/heroic-features/ -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookstore</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">

  </head>

  <body>

    {% include "nav.html" %}

    <!-- Page Content -->
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <!-- /.container -->

    <!-- Bootstrap core JavaScript -->
    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

myproject/core/templates/core/book_add.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="col-sm-6">
  <h1>Novo Livro</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-sm btn-primary">Salvar</button>
  </form>

</div>
{% endblock content %}

myproject/core/templates/core/book_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="row text-center">
    <div class="col-lg-3 col-md-6 mb-4">
      <a class="btn btn-default" href="{% url 'core:index' %}">Voltar</a>
      <div class="card">
        {% if book.cover %}
          <img class="card-img-top" src="{{ book.cover }}" alt="">
        {% else %}
          <img class="card-img-top" src="http://placehold.it/500x325" alt="">
        {% endif %}
        <div class="card-body">
          <h4 class="card-title">{{ book.title }}</h4>
          <p class="card-text">{{ book.author }}</p>
          <p class="card-text">{{ book.year_publication }}</p>
          <p class="card-text">{{ book.publisher }}</p>
        </div>
        <!-- <div class="card-footer">
          <a href="#" class="btn btn-primary">Detalhes</a>
        </div> -->
      </div>
    </div>
  </div>
{% endblock content %}

myproject/core/templates/core/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Lista de Livros</h1>
  {% if book_list %}
    <div class="row text-center">

      {% for book in book_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            {% if book.cover %}
              <img class="card-img-top" src="{{ book.cover }}" alt="">
            {% else %}
              <img class="card-img-top" src="http://placehold.it/500x325" alt="">
            {% endif %}
            <div class="card-body">
              <h4 class="card-title">{{ book.title }}</h4>
              <p class="card-text">{{ book.author }}</p>
              <p class="card-text">{{ book.year_publication }}</p>
              <p class="card-text">{{ book.publisher }}</p>
            </div>
            <div class="card-footer">
              <a href="{{ book.get_absolute_url }}" class="btn btn-primary">Detalhes</a>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}
{% endblock content %}

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h1 class="display-3">Bookstore</h1>
    <p class="lead">Exemplo do uso de Funções e Classes no Django.</p>
    <a href="https://github.com/rg3915/django-fbv-cbv-example" target="_blank" class="btn btn-primary btn-lg">GitHub</a>
    <a href="{% url 'core:book_add' %}" class="btn btn-success btn-lg">Novo Livro</a>
  </header>

  <!-- Page Features -->
  {% if book_list %}
    <div class="row text-center">

      {% for book in book_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            {% if book.cover %}
              <img class="card-img-top" src="{{ book.cover }}" alt="">
            {% else %}
              <img class="card-img-top" src="http://placehold.it/500x325" alt="">
            {% endif %}
            <div class="card-body">
              <h4 class="card-title">{{ book.title }}</h4>
              <p class="card-text">{{ book.author }}</p>
              <p class="card-text">{{ book.year_publication }}</p>
              <p class="card-text">{{ book.publisher }}</p>
            </div>
            <div class="card-footer">
              <a href="{{ book.get_absolute_url }}" class="btn btn-primary">Detalhes</a>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}
  <!-- /.row -->

{% endblock content %}

myproject/core/templates/nav.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'core:index' %}">Bookstore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:index' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:book_list' %}">Bookstore</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/rg3915/django-fbv-cbv-example" target="_blank">GitHub</a>
        </li>
      </ul>
    </div>
  </div>
</nav>